## Load packages

In [1]:
!mamba install -c nvidia cuda-nvcc

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['cuda-nvcc']

nvidia/linux-64                                             Using cache
nvidia/noarch                                               Using cache
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /srv/conda/envs/notebook

  All requested packages already installed

In [1]:
!pip install tables

Collecting tables
  Using cached tables-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
Requirement already satisfied: cython>=0.29.21 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from tables) (0.29.33)
Collecting blosc2~=2.0.0
  Using cached blosc2-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.9 MB)
Requirement already satisfied: packaging in /srv/conda/envs/notebook/lib/python3.10/site-packages (from tables) (23.0)
Requirement already satisfied: numpy>=1.19.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from tables) (1.23.5)
Collecting numexpr>=2.6.2
  Using cached numexpr-2.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (381 kB)
Collecting py-cpuinfo
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: msgpack in /srv/conda/envs/notebook/lib/python3.10/site-packages (from blosc2~=2.0.0->tables) (1.0.4)
Installing collected packages: py-cpuinfo, numexpr, blosc2, tables
Successfully installed blosc2-2.0.0 numexpr-2.8.4 py-cpuinfo-9.0.0 tables-3.8.0

In [1]:

# Autoreload packages that are modified
%load_ext autoreload
%autoreload 2
import h5py
import os
import sys
import xarray as xr
#import tensorflow as tf
#print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
#if tf.test.is_gpu_available():
    #print('GPU is available')
#else:
    #print('GPU is not available')

#device_name = '/gpu:0'
#ds = xr.open_dataset('forecast_rodeo/data/dataframes/gt-contest_tmax-14d-1979-2018.h5')


####### Initial version #########

# Ensure correct working directory
#if os.path.basename(os.getcwd()) == "experiments":
    #os.chdir(os.path.join("..",".."))
##f1 = h5py.File('data/dataframes/gt-contest_tmax-14d-1979-2018.h5','r')

##Adds 'experiments' folder to path to load experiments_util
#sys.path.insert(0, 'src/experiments')
## Load general utility functions
#from experiments_util import *

######## CloubBucket Hub version ########
import os
import gcsfs
import xarray as xr

#os.environ['PERSISTENT_BUCKET']
#fs = gcsfs.GCSFileSystem()
sys.path.insert(0, 'src/experiments')

if os.path.basename(os.getcwd()) == "experiments":
    os.chdir(os.path.join("..",".."))
from experiments_util2 import *

## Create (shared) data matrices

Generates two data matrices containing all needed features that vary by date only (create_date_data) or by date and latitude/longitude (create_lat_lon_date_data) and saves them to results/regression/shared.

In [2]:

gt_id = "contest_tmp2m" # "contest_precip" or "contest_tmp2m"
target_horizon = "56w" # "34w" or "56w"
experiment = "regression1"
#os.environ['XLA_FLAGS'] = '--xla_gpu_cuda_data_dir=/srv/conda/envs/notebook'
multiflux_resolution = "monthly" #"monthly" or "daily"


date_cols = create_date_data(gt_id, target_horizon, experiment, multiflux_resolution)
lat_lon_date_cols = create_lat_lon_date_data(gt_id, target_horizon, experiment, multiflux_resolution,
                                             forecast_models=["nmme","nmme0"])

Loading date features
Getting mei_shift59
Elapsed: 0.3507533073425293s
Getting mjo_shift31
Elapsed: 0.17191100120544434s
Getting pca_sst_2010_shift44
Elapsed: 0.22885441780090332s
Getting pca_icec_2010_shift44
Elapsed: 0.08002138137817383s
Getting pca_wind_hgt_10_2010_shift44
Elapsed: 0.13086819648742676s
Getting pca_wind_hgt_100_2010_shift44
Elapsed: 0.13170433044433594s
Getting pca_wind_hgt_500_2010_shift44
Elapsed: 0.1450965404510498s
Getting pca_wind_hgt_850_2010_shift44
Elapsed: 0.22970080375671387s
             0
0   2001-01-01
1   2001-02-01
2   2001-03-01
3   2001-04-01
4   2001-05-01
..         ...
247 2021-08-01
248 2021-09-01
249 2021-10-01
250 2021-11-01
251 2021-12-01

[252 rows x 1 columns]
Elapsed: 9.298324584960938e-06s
             0
0   2001-01-01
1   2001-02-01
2   2001-03-01
3   2001-04-01
4   2001-05-01
..         ...
247 2021-08-01
248 2021-09-01
249 2021-10-01
250 2021-11-01
251 2021-12-01

[252 rows x 1 columns]
Elapsed: 2.3126602172851562e-05s
      start_date  mei_shift59  mei_rank_shift59  nip_shift59  phase_shift31  \
0     1979-01-01        0.003              33.0          3.0            NaN
1     1979-01-02        0.003              33.0          3.0            NaN
2     1979-01-03        0.003              33.0          3.0            NaN
3     1979-01-04        0.003              33.0          3.0            NaN
4     1979-01-05        0.003              33.0          3.0            NaN
...          ...          ...               ...          ...            ...
14698 2021-08-01          NaN               NaN          NaN            NaN
14699 2021-09-01          NaN               NaN          NaN            NaN
14700 2021-10-01          NaN               NaN          NaN            NaN
14701 2021-11-01          NaN               NaN          NaN            NaN
14702 2021-12-01          NaN               NaN          NaN            NaN

       amplitude_shift31  sst_2010_1_shift44  sst_2010_2_shift44  \
0                    NaN                 NaN                 NaN
1                    NaN                 NaN                 NaN
2                    NaN                 NaN                 NaN
3                    NaN                 NaN                 NaN
4                    NaN                 NaN                 NaN
...                  ...                 ...                 ...
14698                NaN                 NaN                 NaN
14699                NaN                 NaN                 NaN
14700                NaN                 NaN                 NaN
14701                NaN                 NaN                 NaN
14702                NaN                 NaN                 NaN

       sst_2010_3_shift44  sst_2010_4_shift44  ...  \
0                     NaN                 NaN  ...
1                     NaN                 NaN  ...
2                     NaN                 NaN  ...
3                     NaN                 NaN  ...
4                     NaN                 NaN  ...
...                   ...                 ...  ...
14698                 NaN                 NaN  ...
14699                 NaN                 NaN  ...
14700                 NaN                 NaN  ...
14701                 NaN                 NaN  ...
14702                 NaN                 NaN  ...

       wind_hgt_850_2010_1_shift44  wind_hgt_850_2010_2_shift44  \
0                      3966.769235                 -2196.539352
1                      4067.943370                 -2289.876918
2                      4170.111840                 -2384.525933
3                      4175.824952                 -2437.434489
4                      4061.822341                 -2387.403068
...                            ...                          ...
14698                          NaN                          NaN
14699                          NaN                          NaN
14700                          NaN                          NaN
14701                          NaN                          NaN
14702                          NaN                          NaN

       wind_hgt_850_2010_3_shift44  wind_hgt_850_2010_4_shift44  \
0                       -79.748384                   576.961658
1                        35.215968                   571.998097
2                       175.368169                   587.216909
3                       347.902153                   598.531244
4                       529.734680                   565.045388
...                            ...                          ...
14698                          NaN                          NaN
14699                          NaN                          NaN
14700                          NaN                          NaN
14701                          NaN                          NaN
14702                          NaN                          NaN

       wind_hgt_850_2010_5_shift44  wind_hgt_850_2010_6_shift44  \
0                     -1039.460514                  -855.667596
1                      -996.506803                  -699.620739
2                      -917.834174                  -547.003173
3                      -852.309441                  -393.462001
4                      -795.088959                  -242.027753
...                            ...                          ...
14698                          NaN                          NaN
14699                          NaN                          NaN
14700                          NaN                          NaN
14701                          NaN                          NaN
14702                          NaN                          NaN

       wind_hgt_850_2010_7_shift44  wind_hgt_850_2010_8_shift44  \
0                      -542.680800                  -538.870812
1                      -226.795631                  -384.597829
2                       106.437012                  -224.727307
3                       421.281915                   -88.099549
4                       687.402802                    54.185167
...                            ...                          ...
14698                          NaN                          NaN
14699                          NaN                          NaN
14700                          NaN                          NaN
14701                          NaN                          NaN
14702                          NaN                          NaN

       wind_hgt_850_2010_9_shift44  wind_hgt_850_2010_10_shift44
0                      -588.580487                    154.083264
1                      -482.509920                    -65.369132
2                      -349.115245                   -275.459276
3                      -265.936449                   -441.457765
4                      -295.747368                   -589.749207
...                            ...                           ...
14698                          NaN                           NaN
14699                          NaN                           NaN
14700                          NaN                           NaN
14701                          NaN                           NaN
14702                          NaN                           NaN

[14703 rows x 66 columns]
Loading additional date features
Elapsed: 0.002258777618408203s
Saving date features to results/regression1/shared/contest_tmp2m_56w/date_data-contest_tmp2m_56w.h5
Elapsed: 0.3874623775482178s
Finished generating date_data matrix.
Total time elapsed: 11.633612394332886s
Loading contest mask
Elapsed: 0.0037305355072021484s
Loading lat lon date features
gt_ids ['contest_rhum.sig995', 'contest_pres.sfc.gauss', 'GPP', 'RECO', 'CASM_soil_moisture', 'contest_rhum.sig995', 'contest_pres.sfc.gauss', 'GPP', 'RECO', 'CASM_soil_moisture', 'contest_rhum.sig995', 'contest_pres.sfc.gauss', 'GPP', 'RECO', 'CASM_soil_moisture']
gt_shifts [44, 44, 44, 44, 44, 88, 88, 88, 88, 88, 365, 365, 365, 365, 365]
anom_ids ['contest_tmp2m', 'contest_precip', 'contest_tmp2m', 'contest_precip', 'contest_tmp2m', 'contest_precip', 'contest_tmp2m']
anom_shifts [None, 43, 43, 86, 86, 365, 365]
past_start_deltas [43, 43]
Getting contest_rhum.sig995_shift44
Elapsed: 5.305407524108887s
Getting contest_pres.sfc.gauss_shift44
Elapsed: 11.457210779190063s
Getting GPP_shift44
GPP
Getting : GPP
Index(['GPP'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f5844574670>
         latitude  longitude       time       GPP
0            27.0      236.0 2001-02-14       NaN
1            27.0      236.0 2001-03-17       NaN
2            27.0      236.0 2001-04-14       NaN
3            27.0      236.0 2001-05-15       NaN
4            27.0      236.0 2001-06-14       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2021-09-14  4.745697
2713784      49.0      266.0 2021-10-15  4.021908
2713785      49.0      266.0 2021-11-14  2.503455
2713786      49.0      266.0 2021-12-15  2.196509
2713787      49.0      266.0 2022-01-14  2.124580

[2713788 rows x 4 columns]
Elapsed: 36.22818946838379s
Getting RECO_shift44
RECO
Index(['RECO'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f58273c8ee0>
         latitude  longitude       time      RECO
0            27.0      236.0 2001-02-14       NaN
1            27.0      236.0 2001-03-17       NaN
2            27.0      236.0 2001-04-14       NaN
3            27.0      236.0 2001-05-15       NaN
4            27.0      236.0 2001-06-14       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2021-09-14  4.416244
2713784      49.0      266.0 2021-10-15  3.749616
2713785      49.0      266.0 2021-11-14  2.338751
2713786      49.0      266.0 2021-12-15  2.026108
2713787      49.0      266.0 2022-01-14  1.942994

[2713788 rows x 4 columns]
Elapsed: 36.82026958465576s
Getting CASM_soil_moisture_shift44
CASM_soil_moisture
Getting CASM_soil_moisture
Index(['Unnamed: 0', 'CASM_soil_moisture'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f58279f24d0>
             lat      lon       date  Unnamed: 0  CASM_soil_moisture
0         27.170  245.749 2010-03-02     6039126            0.084919
1         27.170  245.749 2010-03-08     6046308            0.157514
2         27.170  245.749 2010-03-11     6051123            0.092499
3         27.170  245.749 2010-03-14     6056339            0.085496
4         27.170  245.749 2010-03-17     6061906            0.118049
...          ...      ...        ...         ...                 ...
14348401  48.852  265.980 2020-09-29    14314567            0.513210
14348402  48.852  265.980 2020-10-02    14322041            0.474884
14348403  48.852  265.980 2020-10-05    14329552            0.481865
14348404  48.852  265.980 2020-10-08    14336884            0.495370
14348405  48.852  265.980 2020-10-11    14344461            0.486723

[14348406 rows x 5 columns]
test de CASM              lat      lon start_date  Unnamed: 0_shift44  \
0         27.170  245.749 2010-03-02             6039126
1         27.170  245.749 2010-03-08             6046308
2         27.170  245.749 2010-03-11             6051123
3         27.170  245.749 2010-03-14             6056339
4         27.170  245.749 2010-03-17             6061906
...          ...      ...        ...                 ...
14348401  48.852  265.980 2020-09-29            14314567
14348402  48.852  265.980 2020-10-02            14322041
14348403  48.852  265.980 2020-10-05            14329552
14348404  48.852  265.980 2020-10-08            14336884
14348405  48.852  265.980 2020-10-11            14344461

          CASM_soil_moisture_shift44
0                           0.084919
1                           0.157514
2                           0.092499
3                           0.085496
4                           0.118049
...                              ...
14348401                    0.513210
14348402                    0.474884
14348403                    0.481865
14348404                    0.495370
14348405                    0.486723

[14348406 rows x 5 columns]
Elapsed: 37.29882001876831s
Getting contest_rhum.sig995_shift88
Elapsed: 21.328296422958374s
Getting contest_pres.sfc.gauss_shift88
Elapsed: 20.250123739242554s
Getting GPP_shift88
GPP
Getting : GPP
Index(['GPP'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f583a541e10>
         latitude  longitude       time       GPP
0            27.0      236.0 2001-03-30       NaN
1            27.0      236.0 2001-04-30       NaN
2            27.0      236.0 2001-05-28       NaN
3            27.0      236.0 2001-06-28       NaN
4            27.0      236.0 2001-07-28       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2021-10-28  4.745697
2713784      49.0      266.0 2021-11-28  4.021908
2713785      49.0      266.0 2021-12-28  2.503455
2713786      49.0      266.0 2022-01-28  2.196509
2713787      49.0      266.0 2022-02-27  2.124580

[2713788 rows x 4 columns]
Elapsed: 48.37862277030945s
Getting RECO_shift88
RECO
Index(['RECO'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f58273cb370>
         latitude  longitude       time      RECO
0            27.0      236.0 2001-03-30       NaN
1            27.0      236.0 2001-04-30       NaN
2            27.0      236.0 2001-05-28       NaN
3            27.0      236.0 2001-06-28       NaN
4            27.0      236.0 2001-07-28       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2021-10-28  4.416244
2713784      49.0      266.0 2021-11-28  3.749616
2713785      49.0      266.0 2021-12-28  2.338751
2713786      49.0      266.0 2022-01-28  2.026108
2713787      49.0      266.0 2022-02-27  1.942994

[2713788 rows x 4 columns]
Elapsed: 48.329936027526855s
Getting CASM_soil_moisture_shift88
CASM_soil_moisture
Getting CASM_soil_moisture
Index(['Unnamed: 0', 'CASM_soil_moisture'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f5840f932e0>
             lat      lon       date  Unnamed: 0  CASM_soil_moisture
0         27.170  245.749 2010-03-02     6039126            0.084919
1         27.170  245.749 2010-03-08     6046308            0.157514
2         27.170  245.749 2010-03-11     6051123            0.092499
3         27.170  245.749 2010-03-14     6056339            0.085496
4         27.170  245.749 2010-03-17     6061906            0.118049
...          ...      ...        ...         ...                 ...
14348401  48.852  265.980 2020-09-29    14314567            0.513210
14348402  48.852  265.980 2020-10-02    14322041            0.474884
14348403  48.852  265.980 2020-10-05    14329552            0.481865
14348404  48.852  265.980 2020-10-08    14336884            0.495370
14348405  48.852  265.980 2020-10-11    14344461            0.486723

[14348406 rows x 5 columns]
test de CASM              lat      lon start_date  Unnamed: 0_shift44  \
0         27.170  245.749 2010-03-02             6039126
1         27.170  245.749 2010-03-08             6046308
2         27.170  245.749 2010-03-11             6051123
3         27.170  245.749 2010-03-14             6056339
4         27.170  245.749 2010-03-17             6061906
...          ...      ...        ...                 ...
14348401  48.852  265.980 2020-09-29            14314567
14348402  48.852  265.980 2020-10-02            14322041
14348403  48.852  265.980 2020-10-05            14329552
14348404  48.852  265.980 2020-10-08            14336884
14348405  48.852  265.980 2020-10-11            14344461

          CASM_soil_moisture_shift44
0                           0.084919
1                           0.157514
2                           0.092499
3                           0.085496
4                           0.118049
...                              ...
14348401                    0.513210
14348402                    0.474884
14348403                    0.481865
14348404                    0.495370
14348405                    0.486723

[14348406 rows x 5 columns]
Elapsed: 44.122010707855225s
Getting contest_rhum.sig995_shift365
Elapsed: 25.181769847869873s
Getting contest_pres.sfc.gauss_shift365
Elapsed: 24.476667165756226s
Getting GPP_shift365
GPP
Getting : GPP
Index(['GPP'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f5823602b90>
         latitude  longitude       time       GPP
0            27.0      236.0 2002-01-01       NaN
1            27.0      236.0 2002-02-01       NaN
2            27.0      236.0 2002-03-01       NaN
3            27.0      236.0 2002-04-01       NaN
4            27.0      236.0 2002-05-01       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2022-08-01  4.745697
2713784      49.0      266.0 2022-09-01  4.021908
2713785      49.0      266.0 2022-10-01  2.503455
2713786      49.0      266.0 2022-11-01  2.196509
2713787      49.0      266.0 2022-12-01  2.124580

[2713788 rows x 4 columns]
Elapsed: 52.269572496414185s
Getting RECO_shift365
RECO
Index(['RECO'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f582737ba30>
         latitude  longitude       time      RECO
0            27.0      236.0 2002-01-01       NaN
1            27.0      236.0 2002-02-01       NaN
2            27.0      236.0 2002-03-01       NaN
3            27.0      236.0 2002-04-01       NaN
4            27.0      236.0 2002-05-01       NaN
...           ...        ...        ...       ...
2713783      49.0      266.0 2022-08-01  4.416244
2713784      49.0      266.0 2022-09-01  3.749616
2713785      49.0      266.0 2022-10-01  2.338751
2713786      49.0      266.0 2022-11-01  2.026108
2713787      49.0      266.0 2022-12-01  1.942994

[2713788 rows x 4 columns]
Elapsed: 52.59012413024902s
Getting CASM_soil_moisture_shift365
CASM_soil_moisture
Getting CASM_soil_moisture
Index(['Unnamed: 0', 'CASM_soil_moisture'], dtype='object')
<function shift_df_new.<locals>.<lambda> at 0x7f583a541d80>
             lat      lon       date  Unnamed: 0  CASM_soil_moisture
0         27.170  245.749 2010-03-02     6039126            0.084919
1         27.170  245.749 2010-03-08     6046308            0.157514
2         27.170  245.749 2010-03-11     6051123            0.092499
3         27.170  245.749 2010-03-14     6056339            0.085496
4         27.170  245.749 2010-03-17     6061906            0.118049
...          ...      ...        ...         ...                 ...
14348401  48.852  265.980 2020-09-29    14314567            0.513210
14348402  48.852  265.980 2020-10-02    14322041            0.474884
14348403  48.852  265.980 2020-10-05    14329552            0.481865
14348404  48.852  265.980 2020-10-08    14336884            0.495370
14348405  48.852  265.980 2020-10-11    14344461            0.486723

[14348406 rows x 5 columns]
test de CASM              lat      lon start_date  Unnamed: 0_shift44  \
0         27.170  245.749 2010-03-02             6039126
1         27.170  245.749 2010-03-08             6046308
2         27.170  245.749 2010-03-11             6051123
3         27.170  245.749 2010-03-14             6056339
4         27.170  245.749 2010-03-17             6061906
...          ...      ...        ...                 ...
14348401  48.852  265.980 2020-09-29            14314567
14348402  48.852  265.980 2020-10-02            14322041
14348403  48.852  265.980 2020-10-05            14329552
14348404  48.852  265.980 2020-10-08            14336884
14348405  48.852  265.980 2020-10-11            14344461

          CASM_soil_moisture_shift44
0                           0.084919
1                           0.157514
2                           0.092499
3                           0.085496
4                           0.118049
...                              ...
14348401                    0.513210
14348402                    0.474884
14348403                    0.481865
14348404                    0.495370
14348405                    0.486723

[14348406 rows x 5 columns]
Elapsed: 48.181984663009644s

/home/jovyan/forecast_rodeo/src/experiments/experiments_util2.py:862: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return pd.merge(left, right, on=on, how=how)
/home/jovyan/forecast_rodeo/src/experiments/experiments_util2.py:862: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return pd.merge(left, right, on=on, how=how)

           lat    lon  key_2  key_3 start_date  rhum_shift44  pres_shift44  \
0         27.0  261.0    1.0    1.0 1979-01-01     79.020353  98990.379046
1         27.0  261.0    1.0    2.0 1979-01-02     78.185715  98899.980748
2         27.0  261.0    1.0    3.0 1979-01-03     75.412714  98820.342494
3         27.0  261.0    1.0    4.0 1979-01-04     72.435760  98775.896763
4         27.0  261.0    1.0    5.0 1979-01-05     69.272402  98695.539062
...        ...    ...    ...    ...        ...           ...           ...
29740249  49.0  258.0    NaN    NaN 2019-05-23           NaN           NaN
29740250  49.0  259.0    NaN    NaN 2019-05-23           NaN           NaN
29740251  49.0  260.0    NaN    NaN 2019-05-23           NaN           NaN
29740252  49.0  261.0    NaN    NaN 2019-05-23           NaN           NaN
29740253  49.0  262.0    NaN    NaN 2019-05-23           NaN           NaN

          GPP_shift44  RECO_shift44  Unnamed: 0_shift44_x  ...  \
0                 NaN           NaN                   NaN  ...
1                 NaN           NaN                   NaN  ...
2                 NaN           NaN                   NaN  ...
3                 NaN           NaN                   NaN  ...
4                 NaN           NaN                   NaN  ...
...               ...           ...                   ...  ...
29740249          NaN           NaN                   NaN  ...
29740250          NaN           NaN                   NaN  ...
29740251          NaN           NaN                   NaN  ...
29740252          NaN           NaN                   NaN  ...
29740253          NaN           NaN                   NaN  ...

          tmp2m_shift43_anom  precip_shift86  precip_shift86_clim  \
0                        NaN       15.042426            32.602009
1                        NaN        9.003459            32.180107
2                        NaN        7.552290            31.187021
3                        NaN        7.448506            29.856525
4                        NaN        7.448506            29.678614
...                      ...             ...                  ...
29740249                 NaN             NaN                  NaN
29740250                 NaN             NaN                  NaN
29740251                 NaN             NaN                  NaN
29740252                 NaN             NaN                  NaN
29740253                 NaN             NaN                  NaN

          precip_shift86_anom  tmp2m_shift86  tmp2m_sqd_shift86  \
0                  -17.559582            NaN                NaN
1                  -23.176648            NaN                NaN
2                  -23.634731            NaN                NaN
3                  -22.408019            NaN                NaN
4                  -22.230107            NaN                NaN
...                       ...            ...                ...
29740249                  NaN            NaN                NaN
29740250                  NaN            NaN                NaN
29740251                  NaN            NaN                NaN
29740252                  NaN            NaN                NaN
29740253                  NaN            NaN                NaN

          tmp2m_std_shift86  tmp2m_shift86_clim  tmp2m_shift86_anom  \
0                       NaN           24.263987                 NaN
1                       NaN           24.144876                 NaN
2                       NaN           24.006578                 NaN
3                       NaN           23.898624                 NaN
4                       NaN           23.788988                 NaN
...                     ...                 ...                 ...
29740249                NaN                 NaN                 NaN
29740250                NaN                 NaN                 NaN
29740251                NaN                 NaN                 NaN
29740252                NaN                 NaN                 NaN
29740253                NaN                 NaN                 NaN

          precip_shift365
0                7.204428
1                4.798007
2                1.671834
3                1.171708
4                3.176525
...                   ...
29740249       100.714169
29740250        45.460673
29740251        61.931758
29740252        56.646983
29740253        28.687209

[29740254 rows x 61 columns]
Elapsed: 125.90986561775208s
Getting contest_tmp2m_shift365 with anomalies
           lat    lon  key_2  key_3 start_date  rhum_shift44  pres_shift44  \
0         27.0  261.0      1      1 1979-01-01     79.020353  98990.379046
1         27.0  261.0      1      2 1979-01-02     78.185715  98899.980748
2         27.0  261.0      1      3 1979-01-03     75.412714  98820.342494
3         27.0  261.0      1      4 1979-01-04     72.435760  98775.896763
4         27.0  261.0      1      5 1979-01-05     69.272402  98695.539062
...        ...    ...    ...    ...        ...           ...           ...
29740249  49.0  258.0      5     23 2019-05-23           NaN           NaN
29740250  49.0  259.0      5     23 2019-05-23           NaN           NaN
29740251  49.0  260.0      5     23 2019-05-23           NaN           NaN
29740252  49.0  261.0      5     23 2019-05-23           NaN           NaN
29740253  49.0  262.0      5     23 2019-05-23           NaN           NaN

          GPP_shift44  RECO_shift44  Unnamed: 0_shift44_x  ...  \
0                 NaN           NaN                   NaN  ...
1                 NaN           NaN                   NaN  ...
2                 NaN           NaN                   NaN  ...
3                 NaN           NaN                   NaN  ...
4                 NaN           NaN                   NaN  ...
...               ...           ...                   ...  ...
29740249          NaN           NaN                   NaN  ...
29740250          NaN           NaN                   NaN  ...
29740251          NaN           NaN                   NaN  ...
29740252          NaN           NaN                   NaN  ...
29740253          NaN           NaN                   NaN  ...

          tmp2m_sqd_shift86  tmp2m_std_shift86  tmp2m_shift86_clim  \
0                       NaN                NaN           24.263987
1                       NaN                NaN           24.144876
2                       NaN                NaN           24.006578
3                       NaN                NaN           23.898624
4                       NaN                NaN           23.788988
...                     ...                ...                 ...
29740249                NaN                NaN                 NaN
29740250                NaN                NaN                 NaN
29740251                NaN                NaN                 NaN
29740252                NaN                NaN                 NaN
29740253                NaN                NaN                 NaN

          tmp2m_shift86_anom  precip_shift365  precip_shift365_clim  \
0                        NaN         7.204428             12.476616
1                        NaN         4.798007             13.228972
2                        NaN         1.671834             13.862281
3                        NaN         1.171708             14.297970
4                        NaN         3.176525             14.175521
...                      ...              ...                   ...
29740249                 NaN       100.714169             28.369879
29740250                 NaN        45.460673             29.456995
29740251                 NaN        61.931758             29.469751
29740252                 NaN        56.646983             26.299435
29740253                 NaN        28.687209             28.380033

          precip_shift365_anom  tmp2m_shift365  tmp2m_sqd_shift365  \
0                    -5.272188             NaN                 NaN
1                    -8.430965             NaN                 NaN
2                   -12.190447             NaN                 NaN
3                   -13.126262             NaN                 NaN
4                   -10.998996             NaN                 NaN
...                        ...             ...                 ...
29740249             72.344291       18.578002          352.739108
29740250             16.003678       19.258619          379.739075
29740251             32.462007       18.698177          358.939906
29740252             30.347548       18.613803          356.262640
29740253              0.307176       19.268811          381.428659

          tmp2m_std_shift365
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
29740249            2.756258
29740250            2.973996
29740251            3.052551
29740252            3.128732
29740253            3.184586

[29740254 rows x 66 columns]
Elapsed: 122.52782440185547s
           lat    lon  key_2  key_3 start_date  rhum_shift44  pres_shift44  \
0         27.0  261.0      1      1 1979-01-01     79.020353  98990.379046
1         27.0  261.0      1      2 1979-01-02     78.185715  98899.980748
2         27.0  261.0      1      3 1979-01-03     75.412714  98820.342494
3         27.0  261.0      1      4 1979-01-04     72.435760  98775.896763
4         27.0  261.0      1      5 1979-01-05     69.272402  98695.539062
...        ...    ...    ...    ...        ...           ...           ...
29740249  49.0  258.0      5     23 2019-05-23           NaN           NaN
29740250  49.0  259.0      5     23 2019-05-23           NaN           NaN
29740251  49.0  260.0      5     23 2019-05-23           NaN           NaN
29740252  49.0  261.0      5     23 2019-05-23           NaN           NaN
29740253  49.0  262.0      5     23 2019-05-23           NaN           NaN

          GPP_shift44  RECO_shift44  Unnamed: 0_shift44_x  ...  \
0                 NaN           NaN                   NaN  ...
1                 NaN           NaN                   NaN  ...
2                 NaN           NaN                   NaN  ...
3                 NaN           NaN                   NaN  ...
4                 NaN           NaN                   NaN  ...
...               ...           ...                   ...  ...
29740249          NaN           NaN                   NaN  ...
29740250          NaN           NaN                   NaN  ...
29740251          NaN           NaN                   NaN  ...
29740252          NaN           NaN                   NaN  ...
29740253          NaN           NaN                   NaN  ...

          tmp2m_shift86_clim  tmp2m_shift86_anom  precip_shift365  \
0                  24.263987                 NaN         7.204428
1                  24.144876                 NaN         4.798007
2                  24.006578                 NaN         1.671834
3                  23.898624                 NaN         1.171708
4                  23.788988                 NaN         3.176525
...                      ...                 ...              ...
29740249                 NaN                 NaN       100.714169
29740250                 NaN                 NaN        45.460673
29740251                 NaN                 NaN        61.931758
29740252                 NaN                 NaN        56.646983
29740253                 NaN                 NaN        28.687209

          precip_shift365_clim  precip_shift365_anom  tmp2m_shift365  \
0                    12.476616             -5.272188             NaN
1                    13.228972             -8.430965             NaN
2                    13.862281            -12.190447             NaN
3                    14.297970            -13.126262             NaN
4                    14.175521            -10.998996             NaN
...                        ...                   ...             ...
29740249             28.369879             72.344291       18.578002
29740250             29.456995             16.003678       19.258619
29740251             29.469751             32.462007       18.698177
29740252             26.299435             30.347548       18.613803
29740253             28.380033              0.307176       19.268811

          tmp2m_sqd_shift365  tmp2m_std_shift365  tmp2m_shift365_clim  \
0                        NaN                 NaN            13.877076
1                        NaN                 NaN            13.817056
2                        NaN                 NaN            13.872171
3                        NaN                 NaN            13.829688
4                        NaN                 NaN            13.792283
...                      ...                 ...                  ...
29740249          352.739108            2.756258            14.032610
29740250          379.739075            2.973996            14.407670
29740251          358.939906            3.052551            13.985285
29740252          356.262640            3.128732            13.988793
29740253          381.428659            3.184586            14.512959

          tmp2m_shift365_anom
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
...                       ...
29740249             4.545392
29740250             4.850949
29740251             4.712893
29740252             4.625010
29740253             4.755852

[29740254 rows x 68 columns]
Loading additional lat lon date features
Elapsed: 0.6582872867584229s
Saving lat lon date features to results/regression1/shared/contest_tmp2m_56w/lat_lon_date_data-contest_tmp2m_56w.h5

/home/jovyan/forecast_rodeo/src/experiments/experiments_util2.py:1398: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->floating,key->block4_values] [items->Index(['lat', 'lon'], dtype='object')]

Elapsed: 147.08142066001892s
Finished generating lat_lon_date_data matrix.
Total time elapsed: 1623.5477554798126s